apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-micro
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-micro
  template:
    metadata:
      labels:
        app: auth-micro
    spec:
      imagePullSecrets:
      - name: dockerhubpull
      containers:
        - name: service
          image: prankster08/auth-image:latest
          ports:
            - containerPort: 3001
          env:
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                  name: jwt-secret
                  key: jwt-secret 
---
apiVersion: v1
kind: Service
metadata:
  name: auth-micro
  namespace: production
spec:
  selector:
    app: auth-micro
  ports:
    - port: 3001
      targetPort: 3001
