apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: production
type: Opaque
data:
    jwt-secret: TlFBUUBzREw1bkFTempSRSU4TS1iR3NQK0ZuOWZtZ3E/cStiNiVOcUQrbWNVJFhOWTNkc2t4cjY4QGV3K3VSZz1DdFhUYw==

  